# Generated by Django 4.2.30 on 2026-10-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_account_holder',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_id_number',
            field=models.CharField(blank=True, help_text='MyKad / NRIC / Passport for CHIP Send KYC', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('Maybank', 'Maybank (Malayan Banking Berhad)'), ('CIMB Bank', 'CIMB Bank'), ('Public Bank', 'Public Bank'), ('RHB Bank', 'RHB Bank'), ('Hong Leong Bank', 'Hong Leong Bank'), ('AmBank', 'AmBank'), ('Bank Islam', 'Bank Islam Malaysia'), ('BSN', 'Bank Simpanan Nasional'), ('Affin Bank', 'Affin Bank'), ('Alliance Bank', 'Alliance Bank'), ('Bank Rakyat', 'Bank Kerjasama Rakyat Malaysia'), ('OCBC Bank', 'OCBC Bank (Malaysia)'), ('UOB Bank', 'United Overseas Bank (Malaysia)'), ('HSBC Bank', 'HSBC Bank Malaysia'), ('Standard Chartered', 'Standard Chartered Bank')], max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='chip_send_recipient_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
