# Generated by Django 4.2.30 on 2026-10-05 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sku_prefix', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('dropship_price', models.DecimalField(decimal_places=2, help_text='Price the dropshipper pays HQ (RM)', max_digits=10)),
                ('suggested_retail_price', models.DecimalField(decimal_places=2, help_text='Recommended selling price to end customer (RM)', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('WM', 'West Malaysia'), ('SABAH', 'Sabah'), ('SARAWAK', 'Sarawak'), ('LABUAN', 'Labuan')], max_length=10, unique=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('colour', models.CharField(max_length=40)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('stock_updated_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'ordering': ['product__name', 'colour', 'sort_order', 'size'],
                'unique_together': {('product', 'size', 'colour')},
            },
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_qty', models.IntegerField()),
                ('new_qty', models.IntegerField()),
                ('reason', models.CharField(choices=[('HQ_UPDATE', 'HQ stock update'), ('ORDER', 'Reserved by order'), ('RESTORE', 'Restored (order cancelled)'), ('ADMIN', 'Admin adjustment')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='catalog.variant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
