# Generated by Django 4.2.30 on 2026-10-05 13:50

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('AWAITING_PAYMENT', 'Awaiting payment'), ('PAID', 'Paid - to ship'), ('SHIPPED', 'Shipped'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NEEDS_REFUND', 'Paid after expiry - needs refund')], default='AWAITING_PAYMENT', max_length=20)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('postcode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(choices=[('Johor', 'Johor'), ('Kedah', 'Kedah'), ('Kelantan', 'Kelantan'), ('Melaka', 'Melaka'), ('Negeri Sembilan', 'Negeri Sembilan'), ('Pahang', 'Pahang'), ('Perak', 'Perak'), ('Perlis', 'Perlis'), ('Pulau Pinang', 'Pulau Pinang'), ('Selangor', 'Selangor'), ('Terengganu', 'Terengganu'), ('W.P. Kuala Lumpur', 'W.P. Kuala Lumpur'), ('W.P. Putrajaya', 'W.P. Putrajaya'), ('Sabah', 'Sabah'), ('Sarawak', 'Sarawak'), ('W.P. Labuan', 'W.P. Labuan')], max_length=40)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('subtotal_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('total_payable', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('stock_reserved', models.BooleanField(default=False)),
                ('courier', models.CharField(blank=True, max_length=50)),
                ('tracking_no', models.CharField(blank=True, max_length=80)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dropshipper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('shipped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Snapshot of dropship price', max_digits=10)),
                ('unit_sell_price', models.DecimalField(decimal_places=2, help_text="Dropshipper's selling price", max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.variant')),
            ],
        ),
    ]
